version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42010:42010"
    volumes:
      - .local:/data
      - .:/usr/local/app
    env_file: .env
    stdin_open: true
    tty: true