FROM python:3-buster

WORKDIR /usr/src/app

RUN apt-get update -y
RUN apt-get install -y python3 python3-pip
RUN pip3 install psutil

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
RUN python3 setup.py build
RUN python3 setup.py install

EXPOSE 42010

ENTRYPOINT maloja run